# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    sign.manager:
        class: AppBundle\Manager\SignManager
        arguments: ["@doctrine.orm.default_entity_manager"]
    game.manager:
        class: AppBundle\Manager\GameManager
        arguments: ["@session"]
    game_round.manager:
        class: AppBundle\Manager\GameRoundManager
        arguments: ["@game.manager", "@sign.manager"]
